Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: SonarQube Scan
+name: SonarQube report analysis and Quality gate
 
 on:
   push:
@@ -27,3 +27,14 @@ jobs:
           -Dsonar.projectKey=QulityGateTest
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        
+    - name: Check SonarQube Quality Gate
+      run: |
+        STATUS=$(curl -s "http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=QulityGateTest" -u "4bfeceb86030431b89e0f94ac01e996405e8f016" | jq -r '.projectStatus.status')
+        echo "SonarQube Quality Gate Status: $STATUS"
+        if [ "$STATUS" != "OK" ]; then
+          echo "SonarQube Quality Gate Failed. Status: $STATUS"
+          exit 1
+        else
+          echo "SonarQube Quality gate passed!! Status: $STATUS" 
+        fi
