Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,11 +10,14 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: SonarQube Scan
+    - name: Check SonarQube Quality Gate
       run: |
-        sonar-scanner \
-          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
-          -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }}
+        STATUS=$(curl -s "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" -u "${{ secrets.SONAR_LOGIN_TOKEN }}":)
+        echo "SonarQube Quality Gate Status: $STATUS"
+        if [ "$STATUS" == '{"projectStatus":{"status":"ERROR"}}' ]; then
+        echo "SonarQube Quality Gate Failed"
+        gh pr review --approve --body "SonarQube Quality Gate Failed" --event "COMMENT"
+        exit 1
+        fi
+      continue-on-error: true
+
