remove unwanted spaces main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,13 +12,11 @@ jobs:
     steps:
     - name: Check SonarQube Quality Gate
       run: |
-        STATUS=$(curl -s " http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=QulityGateTest" -u "4bfeceb86030431b89e0f94ac01e996405e8f016":jq -r '.projectStatus.status')
+        STATUS=$(curl -s "http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=QulityGateTest" -u "4bfeceb86030431b89e0f94ac01e996405e8f016" | jq -r '.projectStatus.status')
         echo "SonarQube Quality Gate Status: $STATUS"
-        if [["$STATUS" != "OK" ]]; then
-         echo "SonarQube Quality Gate Failed Status $STATUS"
-         exit 1
+        if [ "$STATUS" != "OK" ]; then
+          echo "SonarQube Quality Gate Failed. Status: $STATUS"
+          exit 1
         else
-         echo "SonarQube Quality gate passed !! Status : $STATUS" 
+          echo "SonarQube Quality gate passed!! Status: $STATUS" 
         fi
-      
-
