update status condition in main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,12 +12,13 @@ jobs:
     steps:
     - name: Check SonarQube Quality Gate
       run: |
-        STATUS=$(curl -s " http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=QulityGateTest" -u "4bfeceb86030431b89e0f94ac01e996405e8f016":)
+        STATUS=$(curl -s " http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=QulityGateTest" -u "4bfeceb86030431b89e0f94ac01e996405e8f016":jq -r '.projectStatus.status')
         echo "SonarQube Quality Gate Status: $STATUS"
-        if [ "$STATUS" == '{"projectStatus":{"status":"ERROR"}}' ]; then
-        echo "SonarQube Quality Gate Failed"
-        gh pr review --approve --body "SonarQube Quality Gate Failed" --event "COMMENT"
-        exit 1
+        if [["$STATUS" != "OK" ]]; then
+         echo "SonarQube Quality Gate Failed Status $STATUS"
+         exit 1
+        else
+         echo "SonarQube Quality gate passed !! Status : $STATUS" 
         fi
-      continue-on-error: true
+      
 
