remove unwanted analysis workflow

diff --git a/.github/workflows/pushAnalysis.yaml b/.github/workflows/pushAnalysis.yaml
--- a/.github/workflows/pushAnalysis.yaml
+++ b/.github/workflows/pushAnalysis.yaml
@@ -1,62 +1,40 @@
-name: Quality gate staus on push event
+name: SonarQube report analysis and Quality gate
 
 on:
   push:
     branches:
-      - "*"
+      - '*'
 
 jobs:
   sonarqube:
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        containers: [1]
-
+    
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: 14
+    - name: Set up Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: 14
 
-      - name: Run Cypress tests and upload results to Cypress Dashboard
-        run: |
-            npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
-        env:
-            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-  
-      - name: Generate HTML report from Cypress Dashboard
-        run: |
-            npx marge https://dashboard.cypress.io/projects/<your-dashboard-project-id>/runs
-        env:
-            DASHBOARD_PROJECT_ID: <your-dashboard-project-id>
-            DASHBOARD_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-
-      - name: Build and analyze the project with SonarQube
-        run: |
-          npm install -g sonarqube-scanner
-          sonar-scanner \
-            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
-            -Dsonar.source=./src \
-            -Dsonar.test=./cypress \
-            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
-            -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} \
-            -Dsonar.javascript.lcov.reportPaths=./combinedReports/lcov.info
-            
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-
-      - name: Check quality gate status
-        run: |
-          RESPONSE=$(curl -s "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=QulityGateTest" -u "${{ secrets.SONAR_TOKEN }}")
-          STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')
-
-          if [ "$STATUS" != "OK" ]; then
-            echo "SonarQube Quality Gate Failed !!"
-            exit 1
-          else
-            echo "SonarQube Quality Gate passed !!"
-          fi
+    - name: SonarQube Scan
+      run: |
+        npm install -g sonarqube-scanner
+        sonar-scanner \
+          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
+          -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} \
+          -Dsonar.projectKey=QulityGateTest
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        
+    - name: Check SonarQube Quality Gate
+      run: |
+        STATUS=$(curl -s "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=QulityGateTest" -u "4bfeceb86030431b89e0f94ac01e996405e8f016" | jq -r '.projectStatus.status')
+       
+        if [ "$STATUS" != "OK" ]; then
+          echo "SonarQube Quality Gate Failed !!"
+          exit 1
+        else
+          echo "SonarQube Quality Gate passed !!" 
+        fi
